# Generated by Django 3.0.4 on 2020-04-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBank',
            fields=[
                ('bank_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=40)),
                ('regist_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MChargeType',
            fields=[
                ('charge_type_code', models.IntegerField(primary_key=True, serialize=False)),
                ('charge_type_name', models.CharField(blank=True, max_length=128, null=True)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_charge_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MContractCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.IntegerField()),
                ('company_name', models.CharField(max_length=128)),
                ('fixed_cost_code', models.IntegerField(blank=True, null=True)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_contract_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCreditCard',
            fields=[
                ('credit_card_code', models.IntegerField(primary_key=True, serialize=False)),
                ('credit_card_name', models.CharField(max_length=40)),
                ('regist_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_credit_card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MEDetailCategory',
            fields=[
                ('e_detail_code', models.IntegerField(primary_key=True, serialize=False)),
                ('e_detail_name', models.CharField(max_length=256)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('expense_code', models.IntegerField()),
            ],
            options={
                'db_table': 'm_e_detail_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MElectronicMoney',
            fields=[
                ('e_money_code', models.IntegerField(primary_key=True, serialize=False)),
                ('e_money_name', models.CharField(max_length=256)),
                ('regist_date', models.DateField()),
                ('regist_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
            ],
            options={
                'db_table': 'm_electronic_money',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MExpenseCategory',
            fields=[
                ('expense_code', models.IntegerField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=40)),
                ('regist_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_expense_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MFixedCostItem',
            fields=[
                ('fixed_cost_code', models.IntegerField(primary_key=True, serialize=False)),
                ('fixed_cost_name', models.CharField(max_length=40)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('expense_code', models.IntegerField(blank=True, null=True)),
                ('payment_cycle_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_fixed_cost_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MGiftCertificate',
            fields=[
                ('gift_certificate_code', models.IntegerField(primary_key=True, serialize=False)),
                ('gift_certificate_name', models.CharField(max_length=256)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('shop_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_gift_certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MMedicalDepartment',
            fields=[
                ('department_code', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=256, null=True)),
                ('regist_date', models.DateField()),
                ('regist_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
            ],
            options={
                'db_table': 'm_medical_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MMedicalInstitution',
            fields=[
                ('medical_code', models.IntegerField(primary_key=True, serialize=False)),
                ('medical_name', models.CharField(blank=True, max_length=256, null=True)),
                ('regist_date', models.DateField()),
                ('regist_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('department_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_medical_institution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MPaymentCycle',
            fields=[
                ('payment_cycle_code', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_cycle_name', models.CharField(max_length=40)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_payment_cycle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MPaymentMethod',
            fields=[
                ('payment_code', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_name', models.CharField(max_length=40)),
                ('regist_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_payment_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MPoint',
            fields=[
                ('point_code', models.IntegerField(primary_key=True, serialize=False)),
                ('point_name', models.CharField(max_length=256)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MQr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.IntegerField()),
                ('qr_name', models.CharField(max_length=40)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'm_qr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MShop',
            fields=[
                ('shop_code', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=256)),
                ('regist_date', models.DateField()),
                ('update_date', models.DateField()),
                ('shop_name_kana', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'm_shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MTax',
            fields=[
                ('tax_code', models.IntegerField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=128, unique=True)),
                ('regist_date', models.DateField()),
                ('regist_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
            ],
            options={
                'db_table': 'm_tax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('user_code', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('regist_date', models.DateField()),
                ('update_date', models.DateField()),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'm_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TChargeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('seq', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('additional_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_charge_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFixedCostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('fixed_cost_code', models.IntegerField()),
                ('payment_code', models.IntegerField()),
                ('credit_card_code', models.IntegerField(blank=True, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=4, null=True)),
                ('usage_start_date', models.DateField()),
                ('usage_end_date', models.DateField(blank=True, null=True)),
                ('company_code', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('point_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_fixed_cost_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TMedicalBills',
            fields=[
                ('treatment_date', models.DateField(primary_key=True, serialize=False)),
                ('burden_amount', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 't_medical_bills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPaymentBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('shop_code', models.IntegerField()),
                ('seq', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_code', models.IntegerField()),
                ('credit_card_code', models.IntegerField(blank=True, null=True)),
                ('e_money_code', models.IntegerField(blank=True, null=True)),
                ('point_code', models.IntegerField(blank=True, null=True)),
                ('gift_certificate_code', models.IntegerField(blank=True, null=True)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('qr_code', models.IntegerField(blank=True, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 't_payment_breakdown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPaymentList',
            fields=[
                ('payment_date', models.DateField(primary_key=True, serialize=False)),
                ('shop_code', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('expense_code', models.IntegerField(blank=True, null=True)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('e_detail_code', models.IntegerField(blank=True, null=True)),
                ('seq', models.IntegerField()),
            ],
            options={
                'db_table': 't_payment_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTaxPayment',
            fields=[
                ('payment_date', models.DateField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('regist_user_code', models.IntegerField()),
                ('regist_date', models.DateField()),
                ('update_user_code', models.IntegerField()),
                ('update_date', models.DateField()),
                ('payment_code', models.IntegerField()),
            ],
            options={
                'db_table': 't_tax_payment',
                'managed': False,
            },
        ),
    ]
